"""Agregar campos de pago a contratos

Revision ID: 002f6d90495c
Revises: b257a4bf099f
Create Date: 2026-04-16 13:49:11.239930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002f6d90495c'
down_revision = 'b257a4bf099f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_period', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_entry', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('payment_entry')
        batch_op.drop_column('payment_period')

    # ### end Alembic commands ###
